Fix panic

diff --git a/e2e-tests/fsck-bad-blob-name b/e2e-tests/fsck-bad-blob-name
--- a/e2e-tests/fsck-bad-blob-name
+++ b/e2e-tests/fsck-bad-blob-name
@@ -1,22 +1,22 @@
 #!/bin/bash
-# Verify that if a data file gets deleted that the matching
-# git repo file is also deleted.
 
 . e2e-tests/help/setup
 
-echo abc 123 > e2etmp/data/foo
-echo abc 124 > e2etmp/data/foo.jpg
+echo "abc 123" > e2etmp/data/foo
+echo "abc 124" > e2etmp/data/foo.jpg
 
 # update and then validate.
 $TB update e2etmp/update.cfg
 $TB fsck e2etmp/update.cfg
 
 # Create a problem in the repo.
-echo abc >> e2etmp/blobs/c5*
+echo "a" >> e2etmp/blobs/a
 
+# This case used to lead to a panic, it should just get a regular exit 1.
+# echo abc >> e2etmp/blobs/abc
 exit_code=0
 $TB fsck e2etmp/update.cfg || exit_code=$?
 if [ $exit_code -ne 1 ]; then
-	echo "Test failed"
+	echo "Test failed with error code: $exit_code"
 	exit 1
 fi
