Changing our e2e-tests working path

diff --git a/e2e-tests/fsck-blob-corrupted b/e2e-tests/fsck-blob-corrupted
--- a/e2e-tests/fsck-blob-corrupted
+++ b/e2e-tests/fsck-blob-corrupted
@@ -2,21 +2,21 @@
 
 . e2e-tests/help/setup
 
-echo "abc 123" > e2etmp/data/foo
-echo "abc 124" > e2etmp/data/foo.jpg
+echo "abc 123" >x/data/foo
+echo "abc 124" >x/data/foo.jpg
 
 # Set our baseline for the test.
-$TB update e2etmp/update.cfg
-$TB fsck e2etmp/update.cfg
+$TB update x/update.cfg
+$TB fsck x/update.cfg
 
 # Create a blob that doesn't match it's name
-mv e2etmp/blobs/79cec447bf708b719ce9fe5a2eb9921393921542d65bbb81ff113d908b56419a \
-   e2etmp/blobs/79cec447bf708b719ce9fe5a2eb9921393921542d65bbb81ff113d908b56419b
+mv x/blobs/79cec447bf708b719ce9fe5a2eb9921393921542d65bbb81ff113d908b56419a \
+    x/blobs/79cec447bf708b719ce9fe5a2eb9921393921542d65bbb81ff113d908b56419b
 
 # Verify we are getting *exactly* exit 1, for example a panic is exit 2.
 exit_code=0
-$TB fsck e2etmp/update.cfg || exit_code=$?
+$TB fsck x/update.cfg || exit_code=$?
 if [ $exit_code -ne 1 ]; then
-	echo "Test failed with error code: $exit_code"
-	exit 1
+    echo "Test failed with error code: $exit_code"
+    exit 1
 fi
diff --git a/e2e-tests/fsck-ref-corrupted b/e2e-tests/fsck-ref-corrupted
--- a/e2e-tests/fsck-ref-corrupted
+++ b/e2e-tests/fsck-ref-corrupted
@@ -2,20 +2,20 @@
 
 . e2e-tests/help/setup
 
-echo abc 123 > e2etmp/data/foo
-echo abc 124 > e2etmp/data/foo.jpg
+echo abc 123 >x/data/foo
+echo abc 124 >x/data/foo.jpg
 
 # Set our baseline for the test.
-$TB update e2etmp/update.cfg
-$TB fsck e2etmp/update.cfg
+$TB update x/update.cfg
+$TB fsck x/update.cfg
 
 # This isn't a valid ref file.
-echo "abc 124" >> e2etmp/git/corrupt.jpg
+echo "abc 124" >>x/git/corrupt.jpg
 
 # Verify we are getting *exactly* exit 1, for example a panic is exit 2.
 exit_code=0
-$TB fsck e2etmp/update.cfg || exit_code=$?
+$TB fsck x/update.cfg || exit_code=$?
 if [ $exit_code -ne 1 ]; then
-	echo "Test failed with error code: $exit_code, Expected: 1."
-	exit 1
+    echo "Test failed with error code: $exit_code, Expected: 1."
+    exit 1
 fi
diff --git a/e2e-tests/fsck-ref-invalid b/e2e-tests/fsck-ref-invalid
--- a/e2e-tests/fsck-ref-invalid
+++ b/e2e-tests/fsck-ref-invalid
@@ -2,15 +2,15 @@
 
 . e2e-tests/help/setup
 
-echo abc 123 > e2etmp/data/foo
-echo abc 124 > e2etmp/data/foo.jpg
+echo abc 123 >x/data/foo
+echo abc 124 >x/data/foo.jpg
 
 # update and then validate.
-$TB update e2etmp/update.cfg
-$TB fsck e2etmp/update.cfg
+$TB update x/update.cfg
+$TB fsck x/update.cfg
 
 # The blob file referenced here doesn't exist.
-cat <<HERE >e2etmp/git/no-sha.jpg
+cat <<HERE >x/git/no-sha.jpg
 {
  "sha256": "c5d982dc040081e09cad25209fed928b334a21fb2ff34db5202178a7b1a81988",
  "unixnano": 1749858394741289104
@@ -18,8 +18,8 @@ cat <<HERE >e2etmp/git/no-sha.jpg
 HERE
 
 exit_code=0
-$TB fsck e2etmp/update.cfg || exit_code=$?
+$TB fsck x/update.cfg || exit_code=$?
 if [ $exit_code -ne 1 ]; then
-	echo "Test failed with error code: $exit_code, Expected: 1."
-	exit 1
+    echo "Test failed with error code: $exit_code, Expected: 1."
+    exit 1
 fi
